<?php
/*
 * @Author:    Dan Lewis (dan.lewis@deploy.co.uk)
 * @Copyright: 2024 Deploy Ecommerce (https://www.deploy.co.uk/)
 * @Package:   DeployEcommerce_DynamicSwatchLink
 */

use Magento\Catalog\Block\Product\View;

/**
 *
 * @var $block View
 */

?>
<?php $_helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
<?php $_product = $block->getProduct(); ?>

<div class="product-add-form">
    <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
          action="<?= $block->escapeUrl($block->getSubmitUrl($_product)) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()) : ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="matrix-flag" value="1"/>
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('form_top') ?>
        <?php if (!$block->hasOptions()) : ?>
            <?= $block->getChildHtml('product_info_form_content') ?>
        <?php else : ?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1') : ?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2') : ?>
            <?= $block->getChildChildHtml('options_container') ?>
        <?php endif; ?>
        <?= $block->getChildHtml('form_bottom') ?>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "[data-role=priceBox][data-price-box=product-id-<?= $block->escapeHtml($_product->getId()) ?>]": {
            "priceBox": {
                "priceConfig": <?= /* @noEscape */
    $block->getJsonConfig() ?>
    }
}
}
</script>
